<a href="https://colab.research.google.com/github/RamaHareshKiran/Algorithms-and-Analysis-Lab/blob/Algorithms/Floyd_Warshall_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np

def floyd_warshall(graph):
    num_vertices = len(graph)
    dist = np.array(graph)

    for k in range(num_vertices):
        for i in range(num_vertices):
            for j in range(num_vertices):
                if dist[i][j] > dist[i][k] + dist[k][j]:
                    dist[i][j] = dist[i][k] + dist[k][j]

    return dist

# Example usage
if __name__ == "__main__":
    # Example graph represented as an adjacency matrix
    graph = [
        [0, 3, np.inf, 7],
        [8, 0, 2, np.inf],
        [5, np.inf, 0, 1],
        [2, np.inf, np.inf, 0]
    ]

    shortest_paths = floyd_warshall(graph)
    print("Shortest path matrix:")
    print(shortest_paths)


Shortest path matrix:
[[0. 3. 5. 6.]
 [5. 0. 2. 3.]
 [3. 6. 0. 1.]
 [2. 5. 7. 0.]]
